import networkx as nx
hollywood_graph = nw.Graph()
hollywood_graph.add_node("vicent casset")
hollywood_graph.add_edge("vicent casset","scott cann")
hollywood_graph.add_edge("vicent casset","james mcavoy")
hollywood_graph.add_edge("scott cann","kevin bacon")
hollywood_graph.add_edge("james mcavoy","kevin bacon")
hollywood_graph.add_edge("james mcavoy","rasario dawson")
hollywood_graph.add_edge("rasario dawson","richard frice")
hollywood_graph.add_edge("kevin bacon","richard frice")
hollywood_graph.add_edge("kevin bacon","lasco atkins")
hollywood_graph.add_edge("kevin bacon","michael fassbender")
hollywood_graph.add_edge("kevin bacon","david crow")
hollywood_graph.add_edge("lasco atkins","noomi rapace")
hollywood_graph.add_edge("noomi rapace","michael fassbender")
